/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Galileo blandón
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmLogin() {
        initComponents();
    }

    public FrmLogin(String sign_in) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PMain = new javax.swing.JPanel();
        PBanner = new javax.swing.JPanel();
        LblBannerImg = new javax.swing.JLabel();
        LblPhrase = new javax.swing.JLabel();
        LblSubPhrase = new javax.swing.JLabel();
        PUserFeatures = new javax.swing.JTabbedPane();
        PSignIn = new javax.swing.JPanel();
        TxtPassword = new javax.swing.JPasswordField();
        LblSignIn = new javax.swing.JLabel();
        LblUsername = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        BtnSignIn = new javax.swing.JButton();
        LblSignInImg = new javax.swing.JLabel();
        PSign = new javax.swing.JPanel();
        LblSingUp = new javax.swing.JLabel();
        LblSignUpUsername = new javax.swing.JLabel();
        TxtSignUpUsername = new javax.swing.JTextField();
        LblSignUpEmail = new javax.swing.JLabel();
        BtnSingUp = new javax.swing.JButton();
        LblSignUpPassword = new javax.swing.JLabel();
        TxtSignUpPassword = new javax.swing.JPasswordField();
        RbtnSignUpMale = new javax.swing.JRadioButton();
        RbtnSingUpFemale = new javax.swing.JRadioButton();
        TxtSignUpEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 31, 61));

        PMain.setBackground(new java.awt.Color(18, 31, 61));

        PBanner.setBackground(new java.awt.Color(18, 31, 61));
        PBanner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LblBannerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avion-de-papel (1).png"))); // NOI18N

        LblPhrase.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LblPhrase.setForeground(new java.awt.Color(255, 255, 255));
        LblPhrase.setText("CONOCE TU NIVEL DE INGLES");

        LblSubPhrase.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LblSubPhrase.setForeground(new java.awt.Color(255, 255, 255));
        LblSubPhrase.setText(" CON NUESTROS DIVERSOS TESTS");

        javax.swing.GroupLayout PBannerLayout = new javax.swing.GroupLayout(PBanner);
        PBanner.setLayout(PBannerLayout);
        PBannerLayout.setHorizontalGroup(
            PBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBannerLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(PBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBannerLayout.createSequentialGroup()
                        .addComponent(LblBannerImg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBannerLayout.createSequentialGroup()
                        .addComponent(LblPhrase)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBannerLayout.createSequentialGroup()
                        .addComponent(LblSubPhrase)
                        .addGap(106, 106, 106))))
        );
        PBannerLayout.setVerticalGroup(
            PBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBannerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LblBannerImg)
                .addGap(55, 55, 55)
                .addComponent(LblPhrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblSubPhrase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PUserFeatures.setBackground(new java.awt.Color(18, 31, 61));
        PUserFeatures.setToolTipText("");
        PUserFeatures.setName(""); // NOI18N
        PUserFeatures.setOpaque(true);

        PSignIn.setBackground(new java.awt.Color(18, 31, 61));
        PSignIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LblSignIn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblSignIn.setForeground(new java.awt.Color(255, 255, 255));
        LblSignIn.setText("SIGN IN");

        LblUsername.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblUsername.setForeground(new java.awt.Color(255, 255, 255));
        LblUsername.setText("Username");

        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });

        LblPassword.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblPassword.setText("Password");

        BtnSignIn.setBackground(new java.awt.Color(102, 255, 102));
        BtnSignIn.setText("SIGN IN");
        BtnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignInActionPerformed(evt);
            }
        });

        LblSignInImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user (1).png"))); // NOI18N

        javax.swing.GroupLayout PSignInLayout = new javax.swing.GroupLayout(PSignIn);
        PSignIn.setLayout(PSignInLayout);
        PSignInLayout.setHorizontalGroup(
            PSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSignInLayout.createSequentialGroup()
                .addGroup(PSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PSignInLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblUsername)
                            .addComponent(LblPassword)))
                    .addGroup(PSignInLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(PSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblSignIn)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignInLayout.createSequentialGroup()
                                .addComponent(LblSignInImg)
                                .addGap(8, 8, 8)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignInLayout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addComponent(BtnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        PSignInLayout.setVerticalGroup(
            PSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignInLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblSignInImg)
                .addGap(39, 39, 39)
                .addComponent(LblUsername)
                .addGap(18, 18, 18)
                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPassword)
                .addGap(18, 18, 18)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(BtnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PUserFeatures.addTab("SIGN IN", PSignIn);

        PSign.setBackground(new java.awt.Color(18, 31, 61));
        PSign.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LblSingUp.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblSingUp.setForeground(new java.awt.Color(255, 255, 255));
        LblSingUp.setText("SIGN UP");

        LblSignUpUsername.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblSignUpUsername.setForeground(new java.awt.Color(255, 255, 255));
        LblSignUpUsername.setText("Username");

        TxtSignUpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSignUpUsernameActionPerformed(evt);
            }
        });

        LblSignUpEmail.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblSignUpEmail.setForeground(new java.awt.Color(255, 255, 255));
        LblSignUpEmail.setText("Email");

        BtnSingUp.setBackground(new java.awt.Color(102, 255, 102));
        BtnSingUp.setText("SIGN UP");
        BtnSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSingUpActionPerformed(evt);
            }
        });

        LblSignUpPassword.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblSignUpPassword.setForeground(new java.awt.Color(255, 255, 255));
        LblSignUpPassword.setText("Password");

        RbtnSignUpMale.setBackground(new java.awt.Color(18, 31, 61));
        buttonGroup1.add(RbtnSignUpMale);
        RbtnSignUpMale.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RbtnSignUpMale.setForeground(new java.awt.Color(255, 255, 255));
        RbtnSignUpMale.setText("Male");

        RbtnSingUpFemale.setBackground(new java.awt.Color(18, 31, 61));
        buttonGroup1.add(RbtnSingUpFemale);
        RbtnSingUpFemale.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RbtnSingUpFemale.setForeground(new java.awt.Color(255, 255, 255));
        RbtnSingUpFemale.setText("Female");

        TxtSignUpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSignUpEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PSignLayout = new javax.swing.GroupLayout(PSign);
        PSign.setLayout(PSignLayout);
        PSignLayout.setHorizontalGroup(
            PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSignLayout.createSequentialGroup()
                .addGroup(PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PSignLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(LblSingUp))
                    .addGroup(PSignLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblSignUpPassword)
                            .addComponent(LblSignUpEmail)
                            .addComponent(LblSignUpUsername)
                            .addComponent(TxtSignUpUsername)
                            .addComponent(TxtSignUpPassword)
                            .addComponent(TxtSignUpEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignLayout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addGroup(PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignLayout.createSequentialGroup()
                        .addComponent(BtnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignLayout.createSequentialGroup()
                        .addComponent(RbtnSingUpFemale)
                        .addGap(10, 10, 10)
                        .addComponent(RbtnSignUpMale)
                        .addGap(14, 14, 14))))
        );
        PSignLayout.setVerticalGroup(
            PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSignLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblSignUpUsername)
                .addGap(18, 18, 18)
                .addComponent(TxtSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblSignUpEmail)
                .addGap(18, 18, 18)
                .addComponent(TxtSignUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblSignUpPassword)
                .addGap(18, 18, 18)
                .addComponent(TxtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnSignUpMale)
                    .addComponent(RbtnSingUpFemale))
                .addGap(27, 27, 27)
                .addComponent(BtnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        PUserFeatures.addTab("SIGN UP", PSign);

        javax.swing.GroupLayout PMainLayout = new javax.swing.GroupLayout(PMain);
        PMain.setLayout(PMainLayout);
        PMainLayout.setHorizontalGroup(
            PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PUserFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PMainLayout.setVerticalGroup(
            PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMainLayout.createSequentialGroup()
                .addGroup(PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PUserFeatures))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtSignUpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSignUpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSignUpEmailActionPerformed

    private void BtnSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSingUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSingUpActionPerformed

    private void TxtSignUpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSignUpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSignUpUsernameActionPerformed

    private void BtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSignInActionPerformed

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSignIn;
    private javax.swing.JButton BtnSingUp;
    private javax.swing.JLabel LblBannerImg;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPhrase;
    private javax.swing.JLabel LblSignIn;
    private javax.swing.JLabel LblSignInImg;
    private javax.swing.JLabel LblSignUpEmail;
    private javax.swing.JLabel LblSignUpPassword;
    private javax.swing.JLabel LblSignUpUsername;
    private javax.swing.JLabel LblSingUp;
    private javax.swing.JLabel LblSubPhrase;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JPanel PBanner;
    private javax.swing.JPanel PMain;
    private javax.swing.JPanel PSign;
    private javax.swing.JPanel PSignIn;
    private javax.swing.JTabbedPane PUserFeatures;
    private javax.swing.JRadioButton RbtnSignUpMale;
    private javax.swing.JRadioButton RbtnSingUpFemale;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtSignUpEmail;
    private javax.swing.JPasswordField TxtSignUpPassword;
    private javax.swing.JTextField TxtSignUpUsername;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
