package Ventanas;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dani-
 */
public class FrmPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form FrmPreguntas
     */
    public FrmPreguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PPrincipal = new javax.swing.JPanel();
        LblImagenPregunta = new javax.swing.JLabel();
        LblPregunta = new javax.swing.JLabel();
        BtnResp1 = new javax.swing.JButton();
        BtnResp2 = new javax.swing.JButton();
        BtnResp3 = new javax.swing.JButton();
        BtnResp4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Ingles Pregunta #");
        setResizable(false);

        PPrincipal.setBackground(new java.awt.Color(18, 31, 61));
        PPrincipal.setPreferredSize(new java.awt.Dimension(400, 400));

        LblImagenPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pregunta (1).png"))); // NOI18N

        LblPregunta.setBackground(new java.awt.Color(255, 255, 255));
        LblPregunta.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        LblPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPregunta.setText("Pregunta");
        LblPregunta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblPregunta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblPregunta.setOpaque(true);

        BtnResp1.setBackground(new java.awt.Color(36, 56, 91));
        BtnResp1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BtnResp1.setForeground(new java.awt.Color(255, 255, 255));
        BtnResp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estrella.png"))); // NOI18N
        BtnResp1.setText("Respuesta 1");
        BtnResp1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResp1.setRolloverEnabled(false);
        BtnResp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResp1MouseEntered(evt);
            }
        });
        BtnResp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResp1ActionPerformed(evt);
            }
        });

        BtnResp2.setBackground(new java.awt.Color(36, 56, 91));
        BtnResp2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BtnResp2.setForeground(new java.awt.Color(255, 255, 255));
        BtnResp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estrella.png"))); // NOI18N
        BtnResp2.setText("Respuesta 2");
        BtnResp2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResp2.setRolloverEnabled(false);
        BtnResp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResp2MouseEntered(evt);
            }
        });

        BtnResp3.setBackground(new java.awt.Color(36, 56, 91));
        BtnResp3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BtnResp3.setForeground(new java.awt.Color(255, 255, 255));
        BtnResp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estrella.png"))); // NOI18N
        BtnResp3.setText("Respuesta 3");
        BtnResp3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResp3.setRolloverEnabled(false);
        BtnResp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResp3MouseEntered(evt);
            }
        });

        BtnResp4.setBackground(new java.awt.Color(36, 56, 91));
        BtnResp4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BtnResp4.setForeground(new java.awt.Color(255, 255, 255));
        BtnResp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estrella.png"))); // NOI18N
        BtnResp4.setText("Respuesta 4");
        BtnResp4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResp4.setRolloverEnabled(false);
        BtnResp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResp4MouseEntered(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(36, 56, 91));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayudar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PPrincipalLayout = new javax.swing.GroupLayout(PPrincipal);
        PPrincipal.setLayout(PPrincipalLayout);
        PPrincipalLayout.setHorizontalGroup(
            PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LblPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnResp1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(BtnResp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnResp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnResp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPrincipalLayout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(LblImagenPregunta)
                .addGap(204, 204, 204)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PPrincipalLayout.setVerticalGroup(
            PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblImagenPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(LblPregunta)
                .addGap(26, 26, 26)
                .addComponent(BtnResp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnResp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnResp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnResp4)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnResp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResp1MouseEntered
        mouseHover(BtnResp1);
    }//GEN-LAST:event_BtnResp1MouseEntered

    private void BtnResp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResp2MouseEntered
        mouseHover(BtnResp2);
    }//GEN-LAST:event_BtnResp2MouseEntered

    private void BtnResp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResp3MouseEntered
        mouseHover(BtnResp3);
    }//GEN-LAST:event_BtnResp3MouseEntered

    private void BtnResp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResp4MouseEntered
        mouseHover(BtnResp4);
    }//GEN-LAST:event_BtnResp4MouseEntered

    private void BtnResp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnResp1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Si no puedes responder una pregunta es porque no estudiaste burro", "Ayuda", 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void mouseHover(JButton btn){
        var buttonColor = btn.getBackground();
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(Color.GREEN);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(buttonColor);
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnResp1;
    private javax.swing.JButton BtnResp2;
    private javax.swing.JButton BtnResp3;
    private javax.swing.JButton BtnResp4;
    private javax.swing.JLabel LblImagenPregunta;
    private javax.swing.JLabel LblPregunta;
    private javax.swing.JPanel PPrincipal;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
